/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Factura;
import Clases.Listas;
import Clases.Reserva;
import Clases.Servicio_Especial;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author RONALDO
 */
public class JD_Servicios_Especiales extends javax.swing.JDialog {

    Listas ls = new Listas();
    Date FechaActual = new Date(System.currentTimeMillis());
    public ArrayList<Integer> Control = new ArrayList<>();

    /**
     * Creates new form Servicios_Especiales
     */
    public JD_Servicios_Especiales(java.awt.Frame parent, boolean modal, Listas ls) {
        super(parent, modal);
        initComponents();
        this.ls = ls;
        LlenarReservas();
        LlenarServicios();
        String newstring = new SimpleDateFormat("dd/MM/yyyy").format(FechaActual);
        fecha_a.setText(newstring);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Img/Logo.png")).getImage());

    }

    void LlenarReservas() {

        this.cbx_Reserva.removeAllItems();
        int control1 = 0, control2 = 0;
        for (Reserva r : ls.getLr().getLista_Reserva()) {
            int a = r.getFechaI().compareTo(FechaActual);
            int b = r.getFechaF().compareTo(FechaActual);
            if ((a <= 0) && (b >= 0)) {
                cbx_Reserva.addItem("Id: " + r.getId() + " Cliente: " + r.getCl().getNombres() + " " + r.getCl().getApellidos());
                int k = ls.getLr().getLista_Reserva().indexOf(r);
                Control.add(k);
            } else {
                control2++;
                break;
            }
            control1++;
        }

    }

    void LlenarServicios() {
        this.cbx_tiposervicio.removeAllItems();
        for (Servicio_Especial se : ls.getLse().getLista_Servicio_Especial()) {
            cbx_tiposervicio.addItem(se.getNombre());
        }
    }

    void registrar() {
        Reserva reser = null;
        Servicio_Especial Serves=null;
        String ko = Integer.toString(ls.getLf().getLista_Factura().size());
        int pos_res = cbx_Reserva.getSelectedIndex();
        reser= ls.getLr().getLista_Reserva().get(Control.get(pos_res));
        
        Factura f = new Factura(ko,
                reser,
                Serves);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha_a = new javax.swing.JLabel();
        cbx_Reserva = new javax.swing.JComboBox<>();
        cbx_tiposervicio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servicios Especiales-Hotel La Casita De La Abuela");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id Reserva-Cliente:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fecha de Registro:");

        fecha_a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fecha_a.setText("\"FECHA\"");

        cbx_Reserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbx_Reserva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbx_tiposervicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbx_tiposervicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tipo de servicio:");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");

        jButton3.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(fecha_a, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbx_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbx_tiposervicio, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fecha_a))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbx_Reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbx_tiposervicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_Reserva;
    private javax.swing.JComboBox<String> cbx_tiposervicio;
    private javax.swing.JLabel fecha_a;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
