/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Cliente;
import Clases.Factura;
import Clases.Habitacion;
import Clases.Listas;
import Clases.Servicio_Especial;
import Clases.Temporada;
import Clases.Tipo_Habitacion;
import Clases.Usuario;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Box;
import javax.swing.ImageIcon;

/**
 *
 * @author RONALDO
 */
public class JF_Principal extends javax.swing.JFrame {

    Date FechaActual = new Date(System.currentTimeMillis());
    Listas ls = new Listas();
    public static Usuario User_Sesion;

    /**
     * Creates new form Principal
     */
    public JF_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Img/Logo.png")).getImage());
        String newstring = new SimpleDateFormat("dd/MM/yyyy").format(FechaActual);
        Factura f=null;
        lbl_Fecha.setText(newstring);
        this.lbl_Nombre.setText("");
        this.lbl_Apellido.setText("");
        this.lbl_Cargo.setText("");
        this.lbl_Doc.setText("");
        CargarTH();
        CargarHabitaciones();
        CargarTemporada();
        CargarServiciosEspeciales();
    }

    public void CargarTH() {
        this.ls.getLth().getLista_Tipo_Habitacion().add(new Tipo_Habitacion("1", "Suite", 300000));
        this.ls.getLth().getLista_Tipo_Habitacion().add(new Tipo_Habitacion("2", "Ejecutiva", 150000));
        this.ls.getLth().getLista_Tipo_Habitacion().add(new Tipo_Habitacion("3", "Basica", 80000));
    }

    public void CargarHabitaciones() {
        this.ls.getLh().getLista_Habitacion().add(new Habitacion("1", this.ls.getLth().getLista_Tipo_Habitacion().get(0)));
        this.ls.getLh().getLista_Habitacion().add(new Habitacion("2", this.ls.getLth().getLista_Tipo_Habitacion().get(1)));
        this.ls.getLh().getLista_Habitacion().add(new Habitacion("3", this.ls.getLth().getLista_Tipo_Habitacion().get(2)));
    }

    public void CargarTemporada() {
        this.ls.getLt().getLista_Temporada().add(new Temporada("0", "Alta", 0.4));
        this.ls.getLt().getLista_Temporada().add(new Temporada("1", "Media", 0.2));
        this.ls.getLt().getLista_Temporada().add(new Temporada("2", "Baja", 0.1));
    }
    public void CargarServiciosEspeciales(){
        this.ls.getLse().getLista_Servicio_Especial().add(new Servicio_Especial("1", "Lavanderia", 35000));
        this.ls.getLse().getLista_Servicio_Especial().add(new Servicio_Especial("2", "Prestamo de Vestuario", 100000));
        this.ls.getLse().getLista_Servicio_Especial().add(new Servicio_Especial("3", "Desayuno Especial", 50000));
        this.ls.getLse().getLista_Servicio_Especial().add(new Servicio_Especial("4", "Transporte en la ciudad", 200000));
    }
    public void CargarNumeroHabitaciones(){
//        this.ls.getLh().getLista_Habitacion().add( new Habitacion(Id, th))
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Fecha = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        lbl_Apellido = new javax.swing.JLabel();
        lbl_Doc = new javax.swing.JLabel();
        lbl_Cargo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel La Casita De La Abuela");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbl_Fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Fecha.setText("\"FECHA\"");

        lbl_Nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Nombre.setText("\"NOMBRE\"");

        lbl_Apellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Apellido.setText("\"APELLIDO\"");

        lbl_Doc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Doc.setText("\"DOCUMENTO\"");

        lbl_Cargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Cargo.setText("\"CARGO\"");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Hotel.png"))); // NOI18N

        jMenu2.setText("Facturacion");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Agendar.png"))); // NOI18N
        jMenuItem3.setText("Modulo Reservas");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AgendarG.png"))); // NOI18N
        jMenuItem3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AgendarG.png"))); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Modulo Facturas");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(jMenuItem4);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cagg.png"))); // NOI18N
        jMenuItem2.setText("Modulo Clientes");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CaggG.png"))); // NOI18N
        jMenuItem2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CaggG.png"))); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Modulo Servicios Especiales");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Administracion");
        jMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Agg.png"))); // NOI18N
        jMenuItem1.setText("Modulo Usuarios");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AggG.png"))); // NOI18N
        jMenuItem1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/AggG.png"))); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Opciones");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(Box.createHorizontalGlue());

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CerrarSesion.png"))); // NOI18N
        jMenuItem5.setText("Cerrar Sesión");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CerrarSesionG.png"))); // NOI18N
        jMenuItem5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CerrarSesionG.png"))); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Doc, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lbl_Cargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(lbl_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Doc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        new JD_LogIn(this, true, this.ls).setVisible(true);
        this.lbl_Nombre.setText(this.User_Sesion.getNombres());
        this.lbl_Apellido.setText(this.User_Sesion.getApellidos());
        this.lbl_Cargo.setText(this.User_Sesion.getTipo_Usuario());
        this.lbl_Doc.setText(this.User_Sesion.getId());
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.User_Sesion = null;
        this.lbl_Nombre.setText("");
        this.lbl_Apellido.setText("");
        this.lbl_Cargo.setText("");
        this.lbl_Doc.setText("");
        new JD_LogIn(this, true, this.ls).setVisible(true);
        this.lbl_Nombre.setText(this.User_Sesion.getNombres());
        this.lbl_Apellido.setText(this.User_Sesion.getApellidos());
        this.lbl_Cargo.setText(this.User_Sesion.getTipo_Usuario());
        this.lbl_Doc.setText(this.User_Sesion.getId());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new JD_Modulo_Usuarios(this, true, this.ls).setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new JD_Reservas(this, true, this.ls).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new JD_Cliente(this, true, this.ls).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new JD_Servicios_Especiales(this, true, this.ls).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel lbl_Apellido;
    private javax.swing.JLabel lbl_Cargo;
    private javax.swing.JLabel lbl_Doc;
    private javax.swing.JLabel lbl_Fecha;
    private javax.swing.JLabel lbl_Nombre;
    // End of variables declaration//GEN-END:variables
}
